protected/models/OrangelotsManufacture.php
<?php

/**
 * This is the model class for table "orangelots_manufacture".
 *
 * The followings are the available columns in table 'orangelots_manufacture':
 * @property integer $id
 * @property string $name
 */
class OrangelotsManufacture extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'orangelots_manufacture';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id', 'numerical', 'integerOnly' => true),
			array('name,alias', 'length', 'max' => 255),
			array('name,alias', 'required'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, name, alias', 'safe', 'on' => 'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array();
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => 'Name',
			'alias' => 'Url',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('alias', $this->alias, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return OrangelotsManufacture the static model class
	 */
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	public static function getList()
	{
		return self::model()->findAll();
	}

    public static function newRules()
    {
        $alias = OrangelotsManufacture::model()->findAll();
        $rules = '';
        $rule = '';
        if (!empty($alias)) {
            foreach ($alias AS $key => $value){
                if($key == 0)
                    $rules.=$value->alias;
                else
                    $rules.='|'.$value->alias;
            }
            if (!empty($rules))
                //$rule='<vendor:'.$rules.'>';
                return $rules;
        }

        /*return array(
            '<parent:new-furniture|used-furniture|orange-blossom-furniture|upcoming-deals-furniture|flash-deals-furniture>/<alias:\w+>/'.$rule=>'orangelots/orangelots-kind/view',
        );*/
    }
}

protected/controllers/OrangelotsManufactureController.php
<?php

class OrangelotsManufactureController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='application.views.layouts.admin';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array('rights');
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{

	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new OrangelotsManufacture;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['OrangelotsManufacture']))
		{
			$model->attributes=$_POST['OrangelotsManufacture'];
            $model->alias = trim($_POST['OrangelotsManufacture']['alias']);
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['OrangelotsManufacture']))
		{
			$model->attributes=$_POST['OrangelotsManufacture'];
            $model->alias = trim($_POST['OrangelotsManufacture']['alias']);
			if($model->save())
				$this->redirect(array('admin'));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('OrangelotsManufacture');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new OrangelotsManufacture('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['OrangelotsManufacture']))
			$model->attributes=$_GET['OrangelotsManufacture'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return OrangelotsManufacture the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=OrangelotsManufacture::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param OrangelotsManufacture $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='orangelots-manufacture-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/orangelotsManufacture/_form.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $model OrangelotsManufacture */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'orangelots-manufacture-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<?php echo $form->errorSummary($model); ?>
	<div class="row">
		<?php echo $form->labelEx($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'name'); ?>
	</div>

    <div class="row">
		<?php echo $form->labelEx($model,'alias'); ?>
		<?php echo $form->textField($model,'alias',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'alias'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save', array('class' => 'btn btn_orange')); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/orangelotsManufacture/_search.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $model OrangelotsManufacture */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'name'); ?>
		<?php echo $form->textField($model,'name',array('size'=>60,'maxlength'=>255)); ?>
	</div>

    <div class="row">
		<?php echo $form->label($model,'alias'); ?>
		<?php echo $form->textField($model,'alias',array('size'=>60,'maxlength'=>255)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/orangelotsManufacture/_view.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $data OrangelotsManufacture */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('name')); ?>:</b>
	<?php echo CHtml::encode($data->name); ?>
	<br />

    <b><?php echo CHtml::encode($data->getAttributeLabel('alias')); ?>:</b>
	<?php echo CHtml::encode($data->alias); ?>
	<br />


</div>

protected/views/orangelotsManufacture/admin.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $model OrangelotsManufacture */

?>

<h1>Manage Orangelots Manufactures</h1>

<?php echo CHtml::link('Create',createUrl('orangelots-manufacture/create'), array('class' => 'btn btn_orange'));?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'orangelots-manufacture-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'name',
		'alias',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
            'template' => '{update}{delete}'
		),
	),
)); ?>

protected/views/orangelotsManufacture/create.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $model OrangelotsManufacture */

$this->breadcrumbs = array(
    'Orangelots Manufactures' => array('index'),
    'Create',
);

$this->menu = array(
    array('label' => 'List OrangelotsManufacture', 'url' => array('index')),
    array('label' => 'Manage OrangelotsManufacture', 'url' => array('admin')),
);
?>
<div class="main_container">
    <div class="row">
        <h1>Create Manufacture</h1>
    </div>
    <?php $this->renderPartial('_form', array('model' => $model)); ?>
</div>

protected/views/orangelotsManufacture/index.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Orangelots Manufactures',
);

$this->menu=array(
	array('label'=>'Create OrangelotsManufacture', 'url'=>array('create')),
	array('label'=>'Manage OrangelotsManufacture', 'url'=>array('admin')),
);
?>

<h1>Orangelots Manufactures</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/orangelotsManufacture/update.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $model OrangelotsManufacture */

$this->breadcrumbs = array(
    'Orangelots Manufactures' => array('index'),
    $model->name => array('view', 'id' => $model->id),
    'Update',
);

$this->menu = array(
    array('label' => 'List OrangelotsManufacture', 'url' => array('index')),
    array('label' => 'Create OrangelotsManufacture', 'url' => array('create')),
    array('label' => 'View OrangelotsManufacture', 'url' => array('view', 'id' => $model->id)),
    array('label' => 'Manage OrangelotsManufacture', 'url' => array('admin')),
);
?>
<div class="main_container">
    <div class="row">
        <h1>Update Manufacture </h1>
    </div>
    <?php $this->renderPartial('_form', array('model' => $model)); ?>
</div>

protected/views/orangelotsManufacture/view.php
<?php
/* @var $this OrangelotsManufactureController */
/* @var $model OrangelotsManufacture */

$this->breadcrumbs=array(
	'Orangelots Manufactures'=>array('index'),
	$model->name,
);

$this->menu=array(
	array('label'=>'List OrangelotsManufacture', 'url'=>array('index')),
	array('label'=>'Create OrangelotsManufacture', 'url'=>array('create')),
	array('label'=>'Update OrangelotsManufacture', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete OrangelotsManufacture', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage OrangelotsManufacture', 'url'=>array('admin')),
);
?>

<h1>View OrangelotsManufacture #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'name',
		'alias',
	),
)); ?>